#!/bin/sh -e
#
# Activate WIFI on Variscite VAR-SOM-MX8X
#

# Include common functions
. /etc/wifi/variscite-wireless

# GPIO pin to supply 3.3V WIFI voltage
WIFI_3V3_GPIO="gpiochip3 16"

# GPIO pin to supply 1.8V WIFI voltage
WIFI_1V8_GPIO="gpiochip3 13"

# GPIO pin to enable WIFI module
WIFI_EN_GPIO="gpiochip3 9"

# GPIO pin to enable BT module
BT_EN_GPIO="gpiochip3 10"

# GPIO pin to control routing of UART signals
# to BT module or SOM connector
BT_BUF_GPIO="gpiochip1 29"

# WIFI MMC host
WIFI_MMC_HOST=5b020000.mmc
WIFI_MMC_PATH="/sys/bus/platform/drivers/sdhci-esdhc-imx"

# Power up WIFI chip
wifi_up()
{
	# Unbind WIFI device from MMC controller
	wifi_mmc_unbind ${WIFI_MMC_PATH} ${WIFI_MMC_HOST}

	# WIFI_3V3 up
	gpioset ${WIFI_3V3_GPIO}=1
	usleep 10000

	# WIFI_1V8 up
	gpioset ${WIFI_1V8_GPIO}=1
	usleep 10000

	# WLAN_EN up
	gpioset ${WIFI_EN_GPIO}=1

	# BT_EN up
	gpioset ${BT_EN_GPIO}=1

	# BT_BUF up
	gpioset ${BT_BUF_GPIO}=0
	
	# Wait at least 150ms
	usleep 200000
	
	# BT_BUF down
	gpioset ${BT_BUF_GPIO}=1

	# BT_EN down
	gpioset ${BT_EN_GPIO}=0
	
	# Bind WIFI device to MMC controller
	wifi_mmc_bind ${WIFI_MMC_PATH} ${WIFI_MMC_HOST}
	
	# Load WIFI driver
	modprobe brcmfmac
}

# Power down WIFI chip
wifi_down()
{
	# Unload WIFI driver
	modprobe -r brcmfmac

	# Unbind WIFI device from MMC controller
	wifi_mmc_unbind ${WIFI_MMC_PATH} ${WIFI_MMC_HOST}

	# WIFI_EN down
	gpioset ${WIFI_EN_GPIO}=0

	# BT_BUF down
	gpioset ${BT_BUF_GPIO}=1

	# BT_EN down
	gpioset ${BT_EN_GPIO}=0
	usleep 10000

	# WIFI_1V8 down
	gpioset ${WIFI_1V8_GPIO}=0

	# WIFI_3V3 down
	gpioset ${WIFI_3V3_GPIO}=0
}

# Return true if WIFI should not be started
wifi_should_not_be_started()
{
	# Do not enable WIFI if it is already up
	[ -d /sys/class/net/wlan0 ] && return 0

	# Do not enable WIFI if booting from SD
	if grep -q mmcblk1 /proc/cmdline; then
		return 0
	fi

	# Do not enable WIFI if booting from eMMC without WIFI
	if ! grep -q WIFI /sys/devices/soc0/machine; then
		return 0
	fi

	return 1
}

# Return true if WIFI should not be stopped
wifi_should_not_be_stopped()
{
	# Do not stop WIFI if booting from SD
	if grep -q mmcblk1 /proc/cmdline; then
		return 0
	fi

	# Do not stop WIFI if booting from eMMC without WIFI
	if ! grep -q WIFI /sys/devices/soc0/machine; then
		return 0
	fi

	return 1
}

# Start WIFI hardware
wifi_start()
{
	# Exit if WIFI should not be started
	wifi_should_not_be_started && exit 0

	# Try starting WIFI hardware
	for i in $(seq 1 3); do
		# Up WIFI
		wifi_up

		# Exit if WIFI interface exists
		wifi_interface_exists "wlan0" && exit 0

		# Down WIFI
		wifi_down

		# Wait enough time for discharge
		sleep 5
	done

	exit 1
}

# Stop WIFI hardware
wifi_stop()
{
	# Exit if WIFI should not be stopped
	wifi_should_not_be_stopped && exit 0

	# WIFI down
	wifi_down
}

###########################
#  Execution starts here  #
###########################
case $1 in
start)
	wifi_start
	;;
stop)
	wifi_stop
	;;
esac

exit 0
