#!/bin/sh -e
#
# Activate 802.15.4 / OpenThread on Variscite VAR-SOM-MX95
#

# Temporary disable OT service.
exit 0

# Include common functions
. /etc/wifi/variscite-wireless
. /etc/gpiochip

# IW612 ID
WIFI_SDIO_ID=0x0205

# WIFI SDIO ID file
WIFI_SDIO_ID_FILE=/sys/class/net/wlan0/device/device

SPI_DEV="/dev/spidev1.0"
SPI_MODE="0"
SPI_SPEED="1000000"
SPI_RESET_DELAY="500"

# btnxpuart fdt device compatible file
BT_FDT="/sys/firmware/devicetree/base/soc/bus@42000000/serial@42590000/bluetooth"

# Use btnxpuart device node to determine if wifi module is iw61x
fdt_has_btnxpuart() {
	# Check if compatible file exists
	if [ ! -e "$BT_FDT/compatible" ]; then
		return 1
	fi

	# Check if compatible with nxp,88w8987-bt
	if ! grep -q "nxp,88w8987-bt" "$BT_FDT/compatible"; then
		return 1
	fi

	# Check if status file exists
	if [ ! -e "$BT_FDT/status" ]; then
		return 1
	fi

	# Check if status is okay
	if ! grep -q "okay" "$BT_FDT/status"; then
		return 1
	fi

	return 0
}

# Start OT hardware
ot_start()
{
	# Exit if BT module is not iw612 according to the device tree
	fdt_has_btnxpuart || exit 0

	# Exit if BT interface is not running, since it manages the reset line
	if [ ! -e "/sys/class/bluetooth/hci0" ]; then
		echo "$(basename $0): Error: variscite-bt must be running"
		exit 1
	fi

	# Kill any running ot-daemon-iwxxx-spi processes
	kill -9 $(pidof ot-daemon-iwxxx-spi) 2>/dev/null || true

	echo "$(basename $0): starting"

	# Disable btnxpuart power save mode
	hcitool cmd 3f 23 03 00 00

	# Start ot-daemon-iwxxx-spi
	URL="spinel+spi://${SPI_DEV}?spi-mode=${SPI_MODE}&spi-speed=${SPI_SPEED}&spi-reset-delay=${SPI_RESET_DELAY}&"
	echo "${URL}"
	ot-daemon-iwxxx-spi "${URL}"
}

# Stop OT hardware
ot_stop()
{
	# Exit if BT module is not iw612 according to the device tree
	fdt_has_btnxpuart || exit 0

	# Kill any running ot-daemon-iwxxx-spi processes
	kill -9 $(pidof ot-daemon-iwxxx-spi) 2>/dev/null || true
}

###########################
#  Execution starts here  #
###########################
case $1 in

start)
	ot_start
	;;
stop)
	ot_stop
	;;
esac

exit 0
