#!/bin/sh -e
#
# Activate 802.15.4 / OpenThread on Variscite VAR-SOM-MX93 and DART-MX93
#

# Include common functions
. /etc/wifi/variscite-wireless
. /etc/gpiochip

# IW612 ID
WIFI_SDIO_ID=0x0205

# WIFI SDIO ID file
WIFI_SDIO_ID_FILE=/sys/class/net/wlan0/device/device

gpio4=$(get_gpiochip "43830000.gpio")
gpio2=$(get_gpiochip "43810000.gpio")

SPI_DEV_SOM="/dev/spidev1.0"
SPI_DEV_DART_SONATA="/dev/spidev0.1"
SPI_MODE="0"
SPI_SPEED="1000000"
SPI_RESET_DELAY="500"

GPIO_DEV_INT_SOM="/dev/${gpio4}"
GPIO_LINE_INT_SOM="29"

GPIO_DEV_INT_DART_SONATA="/dev/${gpio2}"
GPIO_LINE_INT_DART_SONATA="0"

# Return success exit status if SOM is DART-MX93
is_dart_mx93()
{
	grep -q DART-MX93 /sys/devices/soc0/machine
}

is_carrier_sonata()
{
	grep -q Sonata-Board /sys/devices/soc0/machine
}

ot_set_vars()
{
	if is_dart_mx93; then
		if is_carrier_sonata; then
			GPIO_DEV_INT=${GPIO_DEV_INT_DART_SONATA}
			GPIO_LINE_INT=${GPIO_LINE_INT_DART_SONATA}
			SPI_DEV=${SPI_DEV_DART_SONATA}
		else
			echo "DART-MX93 on carrier board DT8M is not supported yet." >&2
			return 1
		fi
	else
		GPIO_DEV_INT=${GPIO_DEV_INT_SOM}
		GPIO_LINE_INT=${GPIO_LINE_INT_SOM}
		SPI_DEV=${SPI_DEV_SOM}
	fi
	return 0
}
# Start OT hardware
ot_start()
{
	# Exit if OT module is not available
	wifi_sdio_exist ${WIFI_SDIO_ID_FILE} || exit 0

	# Exit if OT module is not iw612
	verify_sdio_id ${WIFI_SDIO_ID_FILE} ${WIFI_SDIO_ID} || exit 0

	# Exit if WIFI module is not iw612
	wifi_is_wbe || exit 0

	# Configure global variables for VAR-SOM or DART
	ot_set_vars || exit 0

	# Kill any running ot-daemon-iwxxx-spi processes
	kill -9 $(pidof ot-daemon-iwxxx-spi) 2>/dev/null || true

	echo "$(basename $0): starting"

	# Disable btnxpuart power save mode
	hcitool cmd 3f 23 03 00 00

	# Start ot-daemon-iwxxx-spi
	URL="spinel+spi://${SPI_DEV}?gpio-int-device=${GPIO_DEV_INT}&gpio-int-line=${GPIO_LINE_INT}&spi-mode=${SPI_MODE}&spi-speed=${SPI_SPEED}&spi-reset-delay=${SPI_RESET_DELAY}&"
	echo "${URL}"
	ot-daemon-iwxxx-spi "${URL}"
}

# Stop OT hardware
ot_stop()
{
	# Exit if OT module is not iw612
	verify_sdio_id ${WIFI_SDIO_ID_FILE} ${WIFI_SDIO_ID} || exit 0

	# Kill any running ot-daemon-iwxxx-spi processes
	kill -9 $(pidof ot-daemon-iwxxx-spi) 2>/dev/null || true
}

wifi_is_wbe()
{
	# Read SOM options EEPROM field
	opt=$(i2cget -f -y 0x2 0x52 0x25)

	# Check WIFI bit in SOM options
	if [ $(( $((opt & 0xF)) >> 3 )) -eq 1 ]; then
		return 0
	else
		return 1
	fi
}

###########################
#  Execution starts here  #
###########################
case $1 in

start)
	ot_start
	;;
stop)
	ot_stop
	;;
esac

exit 0
