#!/bin/sh -e
#
# Activate Bluetooth on Variscite VAR-SOM-MX93
#

# Include common functions
. /etc/wifi/variscite-wireless
. /etc/gpiochip

gpio4=$(get_gpiochip "43830080.gpio")

# GPIO pin to enable BT module
BT_EN_GPIO="${gpio4} 15"

# UART device connected to BT module on VAR-SOM-MX93
BT_TTY_DEV_SOM="/dev/ttyLP4"

# IW612 ID
WIFI_SDIO_ID=0x0205

# WIFI SDIO ID file
WIFI_SDIO_ID_FILE=/sys/class/net/wlan0/device/device

# Enable BT via GPIO(s)
bt_enable()
{
	# Power up BT module
	gpioset ${BT_EN_GPIO}=0
	sleep 0.1
	gpioset ${BT_EN_GPIO}=1
	sleep 0.1
}

# Start BT hardware
bt_start()
{
	# Exit if BT module is not available
	wifi_sdio_exist ${WIFI_SDIO_ID_FILE} || exit 0

	# Exit if BT module is not iw612
	verify_sdio_id ${WIFI_SDIO_ID_FILE} ${WIFI_SDIO_ID} || exit 0

	echo "$(basename $0): starting"

	# Enable BT hardware
	bt_enable

	# Kill any running hciattach processes
	kill -9 $(pidof hciattach) 2>/dev/null || true

	# Initialize and attach the BT device
	hciattach ${BT_TTY_DEV_SOM} any 115200 flow
}

# Stop BT hardware
bt_stop()
{
	# Exit if BT module is not iw612
	verify_sdio_id ${WIFI_SDIO_ID_FILE} ${WIFI_SDIO_ID} || exit 0

	# Exit if BT interface is not available
	[ -e /sys/class/bluetooth/hci0 ] || exit 0

	echo "$(basename $0): stopping"

	# Stop BT interface
	hciconfig hci0 down

	# Kill any running hciattach processes
	kill -9 $(pidof hciattach) 2>/dev/null || true

	# Power down BT module
	gpioset ${BT_EN_GPIO}=0
}

###########################
#  Execution starts here  #
###########################
case $1 in

start)
	bt_start
	;;
stop)
	bt_stop
	;;
esac

exit 0
