#!/bin/sh -e
#
# Activate Bluetooth on Variscite DART-6UL / VAR-SOM-6UL
#

# Include common functions
. /etc/wifi/variscite-wireless

# GPIO pin to enable BT module
BT_EN_GPIO="gpiochip4 4"

# UART device connected to BT module
BT_TTY_DEV=/dev/ttymxc1

# Sterling LWB BT firmware
BT_FIRMWARE_LWB=/lib/firmware/brcm/BCM43430A1.hcd

# Sterling LWB5 BT firmware
BT_FIRMWARE_LWB5=/lib/firmware/brcm/BCM4335C0.hcd

# Sterling LWB5 WIFI SDIO ID
WIFI_5G_SDIO_ID=0x4339

# WIFI SDIO ID file
WIFI_SDIO_ID_FILE=/sys/class/net/wlan0/device/device

# Prepare the Bluetooth MAC address argument for brcm_patchram_plus.
# If eth0 or eth1 is present, set the Bluetooth MAC to the highest
# Ethernet MAC address + 1. If no Ethernet MAC addresses are found,
# use the default MAC address provided by the Bluetooth radio.
bt_set_macaddr()
{
	BT_MACADDR=""
	BT_MACADDR_ARG=""

	# Get MAC address of eth0 if available, stripping colons
	if [ -f /sys/class/net/eth0/address ]; then
		eth0_addr=$(cat /sys/class/net/eth0/address | sed 's/://g')
	else
		eth0_addr=""
	fi

	# Get MAC address of eth1 if available, stripping colons
	if [ -f /sys/class/net/eth1/address ]; then
		eth1_addr=$(cat /sys/class/net/eth1/address | sed 's/://g')
	else
		eth1_addr=""
	fi

	# Determine the Bluetooth MAC address if either eth0 or eth1 exists
	if [ -n "$eth0_addr" ] || [ -n "$eth1_addr" ]; then
		# Use the maximum of eth0 and eth1 MAC addresses
		bt_addr=$(max $eth0_addr $eth1_addr)
		# Increment the address by 1
		bt_addr=$((0x$bt_addr + 1))
		# Convert to 12-character uppercase hexadecimal and format as colon-separated
		bt_addr=$(printf '%012X' $bt_addr)
		BT_MACADDR=$(echo $bt_addr | sed 's/\(..\)/\1:/g;s/:$//')
		# Prepare the argument for Bluetooth initialization
		BT_MACADDR_ARG="--bd_addr $BT_MACADDR"
		echo "BT MAC: $BT_MACADDR"
	else
		echo "BT MAC: Using module default"
	fi
}

# Set BT firmware based on WIFI SDIO ID
bt_set_firmware()
{
	# Check if WIFI SDIO ID matches Sterling LWB5 SDIO ID
	if [ "$(cat ${WIFI_SDIO_ID_FILE})" = "${WIFI_5G_SDIO_ID}" ]; then
		BT_FIRMWARE=${BT_FIRMWARE_LWB5}
	else
		BT_FIRMWARE=${BT_FIRMWARE_LWB}
	fi
}

# Enable BT via GPIO(s)
bt_enable()
{
	# Power up BT module
	gpioset ${BT_EN_GPIO}=0
	sleep 1
	gpioset ${BT_EN_GPIO}=1
}

# Start BT hardware
bt_start()
{
	# Exit if booting from SD (BT is not available)
 	grep -q mmcblk0 /proc/cmdline && exit 0

	# Exit if BT module is not available
	wifi_sdio_exist ${WIFI_SDIO_ID_FILE} || exit 0

	# Enable BT hardware
	bt_enable

	# Set BT firmware file 
	bt_set_firmware

	# Set BT MAC addresss
	bt_set_macaddr

	# Start BT firmware loading service
	kill -9 $(pidof brcm_patchram_plus) 2>/dev/null || true
	brcm_patchram_plus \
			--patchram ${BT_FIRMWARE} \
			--enable_hci \
			${BT_MACADDR_ARG} \
			--no2bytes \
			--baudrate 3000000 \
			--scopcm=1,0,0,0,0,0,0,0,0,0 \
			--tosleep 1000 ${BT_TTY_DEV} &
}

# Stop BT hardware
bt_stop()
{
	# Exit if BT interface is not available
	[ -e /sys/class/bluetooth/hci0 ] || exit 0

	# Stop BT interface
	hciconfig hci0 down

	# Stop BT firmware loading service
	kill -9 $(pidof brcm_patchram_plus) 2>/dev/null || true

  	# Power down BT module
	gpioset ${BT_EN_GPIO}=0
}

###########################
#  Execution starts here  #
###########################
case $1 in

start)
	bt_start
	;;
stop)
	bt_stop
	;;
esac

exit 0
