#!/bin/sh -e
#
# Activate WIFI on Variscite DART-6UL / VAR-SOM-6UL for Broadcom WiFi modules
#

# Include common functions
. /etc/wifi/variscite-wireless

# GPIO pin to supply power to WIFI module on DART-6UL-5G
WIFI_PWR_GPIO="gpiochip4 2"

# GPIO pin to enable WIFI module
WIFI_EN_GPIO="gpiochip4 6"

# GPIO pin to enable BT module
BT_EN_GPIO="gpiochip4 4"

# WIFI MMC host
WIFI_MMC_HOST=2190000.mmc
WIFI_MMC_PATH="/sys/bus/platform/drivers/sdhci-esdhc-imx"

# Function to disable a network interface
disable_network_interface() {
	local iface="$1"

	# Check if the interface exists
	if ip link show "$iface" >/dev/null 2>&1; then
		ifconfig "$iface" down
		usleep 100000
	fi
}

# returns the SOM info revision (which provides the WiFi module in use)
# 0: 2.4G LWB
# 1: 5G LW5
# 2: 5G IW611
# 3: 5G IW612
som_rev_info()
{
	SOM_INFO=`i2cget -y 1 0x51 0xfd`
	SOM_INFO_REV=$((SOM_INFO >> 3))
	return $SOM_INFO_REV
}


# Check if SOM is DART-6UL-5G LW5
som_is_dart_6ul_5g_lw5()
{
	som_rev_info
	REV_INFO=$?
	if [ $REV_INFO = 1 ]; then
		return 0
	fi
	return 1
}

# Check if SOM has IW61x chip
som_is_dart6ul_iw61x()
{
	som_rev_info
	REV_INFO=$?
	if [ $REV_INFO = 2 ] || [ $REV_INFO = 3 ]; then
		return 0;
	fi
	return 1
}

# Power up WIFI chip
wifi_up()
{
	# Unbind WIFI device from MMC controller
	wifi_mmc_unbind ${WIFI_MMC_PATH} ${WIFI_MMC_HOST}

	if som_is_dart_6ul_5g_lw5; then
		# WIFI power up
		gpioset -t 0 --chip ${WIFI_PWR_GPIO}=1
		usleep 10000

		# WLAN_EN up
		gpioset -t 0 --chip ${WIFI_EN_GPIO}=1

		# BT_EN up
		gpioset -t 0 --chip ${BT_EN_GPIO}=1

		# Wait at least 150ms
		usleep 200000

		# BT_EN down
		gpioset -t 0 --chip ${BT_EN_GPIO}=0
	else
		# WLAN_EN up
		gpioset -t 0 --chip ${WIFI_EN_GPIO}=1

		# BT_EN up
		gpioset -t 0 --chip ${BT_EN_GPIO}=1

		# Wait at least 150ms
		usleep 200000

		# BT_EN down
		gpioset -t 0 --chip ${BT_EN_GPIO}=0
	fi

	# Bind WIFI device to MMC controller
	wifi_mmc_bind ${WIFI_MMC_PATH} ${WIFI_MMC_HOST}

	# Load WIFI driver
	modprobe brcmfmac
}

# Power down WIFI chip
wifi_down()
{
	# Disable network interface
	disable_network_interface wlan0

	# Unload WIFI driver
	modprobe -r brcmfmac_wcc
	modprobe -r brcmfmac

	# Unbind WIFI device from MMC controller
	wifi_mmc_unbind ${WIFI_MMC_PATH} ${WIFI_MMC_HOST}

	if som_is_dart_6ul_5g_lw5; then
		# WLAN_EN down
		gpioset -t 0 --chip ${WIFI_EN_GPIO}=0

		# BT_EN down
		gpioset -t 0 --chip ${BT_EN_GPIO}=0
		usleep 10000

		# WIFI power down
		gpioset -t 0 --chip ${WIFI_PWR_GPIO}=0
	else
		# WLAN_EN down
		gpioset -t 0 --chip ${WIFI_EN_GPIO}=0

		# BT_EN down
		gpioset -t 0 --chip ${BT_EN_GPIO}=0
	fi
}

# Return true if WIFI should be started
wifi_should_not_be_started()
{
	# Do not enable WIFI if it is already up
	[ -d /sys/class/net/wlan0 ] && return 0

	# Do not enable WIFI if booting from SD          
	if grep -q mmcblk0 /proc/cmdline; then
		return 0
	fi

	# Exit if booting from eMMC without WIFI
	if ! grep -qi WIFI /sys/devices/soc0/machine; then
		return 0
	fi

	return 1
}

# Return true if WIFI should not be stopped
wifi_should_not_be_stopped()
{
	# Do not stop WIFI if booting from SD
	if grep -q mmcblk0 /proc/cmdline; then
		return 0
	fi

	# Do not stop WIFI if booting from eMMC without WIFI
	if ! grep -qi WIFI /sys/devices/soc0/machine; then
		return 0
	fi

	return 1
}

# Start WIFI hardware
wifi_start()
{
	# Exit if WIFI should not be started
	wifi_should_not_be_started && exit 0

	# Try starting WIFI hardware
	for i in $(seq 1 3); do
		# Up WIFI
		wifi_up

		# Exit if WIFI interface exists
		wifi_interface_exists "wlan0" && exit 0

		# Down WIFI
		wifi_down

		# Wait enough time for discharge
		sleep 5
	done

	exit 1
}

# Stop WIFI hardware
wifi_stop()
{
	# Exit if WIFI should not be stopped
	wifi_should_not_be_stopped && exit 0

	# Down WIFI
	wifi_down
}

###########################
#  Execution starts here  #
###########################

if som_is_dart6ul_iw61x; then
	exit 0
fi

case $1 in
start)
	wifi_start
	;;
stop)
	wifi_stop
	;;
esac

exit 0
