readonly CM_CORES=1
readonly CM_SERIES="m7"
readonly CM_DTB_DART="imx95-var-dart-dt8mcustomboard-m7.dtb"
readonly CM_DTB_SONATA="imx95-var-dart-sonata-m7.dtb"
readonly CM_LOAD_ADDR_TCM="0x203c0000"
readonly CM_LOAD_ADDR_AUXVIEW_TCM="0x00000000" # This is a secure alias
readonly FILE_DEFAULT_FW_LINUX="cm_hello_world_cm7.elf.release"
readonly FILE_DEFAULT_FW_U_BOOT="cm_hello_world.bin.release"
