#!/bin/sh -e
#
# Activate 802.15.4 / OpenThread on Variscite VAR-SOM-MX91 and DART-MX91
#

# Include common functions
. /etc/wifi/variscite-wireless
. /etc/gpiochip

# IW612 ID
WIFI_SDIO_ID=0x0205

# WIFI SDIO ID file
WIFI_SDIO_ID_FILE=/sys/class/net/wlan0/device/device

gpio4=$(get_gpiochip "43830080.gpio")

SPI_DEV="/dev/spidev1.0"
SPI_MODE="0"
SPI_SPEED="1000000"

GPIO_DEV_INT="/dev/${gpio4}"
GPIO_LINE_INT="29"

# Return success exit status if SOM is VAR-SOM-MX91
is_var_som_mx91()
{
	grep -q VAR-SOM-MX91 /sys/devices/soc0/machine
}

is_carrier_symphony_v1x()
{
	grep -q 'Symphony-Board v1.x' /sys/devices/soc0/machine
}

has_wbe()
{
    features=$(i2cget -f -y 0x2 0x52 0x25)

    if [ $((features & 0x08)) -ne 0 ]; then
        return 0
    fi

    return 1
}

# Start OT hardware
ot_start()
{
	# Exit if WBE configuration is not available
	has_wbe || exit 0

	is_carrier_symphony_v1x || exit 0

	# Exit if OT module is not available
	wifi_sdio_exist ${WIFI_SDIO_ID_FILE} || exit 0

	# Exit if OT module is not iw612
	verify_sdio_id ${WIFI_SDIO_ID_FILE} ${WIFI_SDIO_ID} || exit 0

	# Kill any running ot-daemon-iwxxx-spi processes
	kill -9 $(pidof ot-daemon-iwxxx-spi) 2>/dev/null || true

	echo "$(basename $0): starting"

	# Disable btnxpuart power save mode
	hcitool cmd 3f 23 03 00 00

	# Start ot-daemon-iwxxx-spi
	URL="spinel+spi://${SPI_DEV}?gpio-int-device=${GPIO_DEV_INT}&gpio-int-line=${GPIO_LINE_INT}&spi-mode=${SPI_MODE}&spi-speed=${SPI_SPEED}&"
	echo "${URL}"
	ot-daemon-iwxxx-spi "${URL}"
}

# Stop OT hardware
ot_stop()
{
	# Exit if WBE configuration is not available
	has_wbe || exit 0

	# Exit if OT module is not iw612
	verify_sdio_id ${WIFI_SDIO_ID_FILE} ${WIFI_SDIO_ID} || exit 0

	# Kill any running ot-daemon-iwxxx-spi processes
	kill -9 $(pidof ot-daemon-iwxxx-spi) 2>/dev/null || true
}

###########################
#  Execution starts here  #
###########################
case $1 in

start)
	ot_start
	;;
stop)
	ot_stop
	;;
esac

exit 0
