#!/bin/sh -e
#
# Activate WIFI on Variscite VAR-SOM-MX7
#

# Include common functions
. /etc/wifi/variscite-wireless

# GPIO pin to enable WIFI module
WIFI_EN_GPIO="gpiochip0 4"

# GPIO pin to enable BT module
BT_EN_GPIO="gpiochip0 14"

# WIFI MMC host
WIFI_MMC_HOST=30b50000.mmc
WIFI_MMC_PATH="/sys/bus/platform/drivers/sdhci-esdhc-imx"

# Power up WIFI chip
wifi_up()
{
	# Unbind WIFI device from MMC controller
	wifi_mmc_unbind ${WIFI_MMC_PATH} ${WIFI_MMC_HOST}

	# WLAN_EN up
	gpioset ${WIFI_EN_GPIO}=1

	# BT_EN up
	gpioset ${BT_EN_GPIO}=1

	# Wait 150ms at least
	usleep 200000

	# BT_EN down
	gpioset ${BT_EN_GPIO}=0

	# Bind WIFI device to MMC controller
	wifi_mmc_bind ${WIFI_MMC_PATH} ${WIFI_MMC_HOST}

	# Load WIFI driver
	modprobe brcmfmac
}

# Power down WIFI chip
wifi_down()
{
	# Unload WIFI driver
	modprobe -r brcmfmac

	# Unbind WIFI device from MMC controller
	wifi_mmc_unbind ${WIFI_MMC_PATH} ${WIFI_MMC_HOST}

	# WLAN_EN down
	gpioset ${WIFI_EN_GPIO}=0

	# BT_EN down
	gpioset ${BT_EN_GPIO}=0
}

# Return true if WIFI should be started
wifi_should_not_be_started()
{
	# Do not enable WIFI if it is already up
	[ -d /sys/class/net/wlan0 ] && return 0

	return 1
}

# Return true if WIFI should not be stopped
wifi_should_not_be_stopped()
{
	# Always stop WIFI
	return 1
}

# Start WIFI hardware
wifi_start()
{
	# Exit if WIFI should not be started
	wifi_should_not_be_started && exit 0

	# Try starting WIFI hardware
	for i in $(seq 1 3); do
		# Up WIFI
		wifi_up

		# Exit if WIFI interface exists
		wifi_interface_exists "wlan0" && exit 0

		# Down WIFI
		wifi_down

		# Wait enough time for discharge
		sleep 5
	done

	exit 1
}

# Stop WIFI hardware
wifi_stop()
{
	# Exit if WIFI should not be stopped
	wifi_should_not_be_stopped && exit 0

	# Down WIFI
	wifi_down
}

###########################
#  Execution starts here  #
###########################
case $1 in
start)
	wifi_start
	;;
stop)
	wifi_stop
	;;
esac

exit 0
