#!/bin/sh -e
#
# Activate Bluetooth on Variscite VAR-SOM-MX7
#

# Include common functions
. /etc/wifi/variscite-wireless

# GPIO pin to enable BT module
BT_EN_GPIO="gpiochip0 14"

# GPIO pin to enable the BT UART/PCM buffer (active low, LWB5 only)
BT_BUF_GPIO="gpiochip0 6"

# UART device connected to BT module
BT_TTY_DEV=/dev/ttymxc2

# Sterling LWB BT firmware
BT_FIRMWARE_LWB=/lib/firmware/brcm/BCM43430A1.hcd

# Sterling LWB5 BT firmware
BT_FIRMWARE_LWB5=/lib/firmware/brcm/BCM4335C0.hcd

# Sterling LWB WIFI SDIO ID
WIFI_2G_SDIO_ID=0xa9a6

# Sterling LWB5 WIFI SDIO ID
WIFI_5G_SDIO_ID=0x4339

# WIFI SDIO ID file
WIFI_SDIO_ID_FILE=/sys/class/net/wlan0/device/device

# Return true if the SOM has a LWB5 (5G) module
bt_is_lwb5()
{
	[ "$(cat "$WIFI_SDIO_ID_FILE")" = "$WIFI_5G_SDIO_ID" ]
}

# Enable the BT UART/PCM buffer on LWB5 modules
bt_buffer_enable()
{
	bt_is_lwb5 || return 0
	gpioset -t 0 --chip ${BT_BUF_GPIO}=0
}

# Disable the BT UART/PCM buffer on LWB5 modules
bt_buffer_disable()
{
	bt_is_lwb5 || return 0
	gpioset -t 0 --chip ${BT_BUF_GPIO}=1
}

# Set BT MAC address
bt_set_macaddr()
{
  eth0_addr=$(cat /sys/class/net/eth0/address | sed 's/\://g')
  eth1_addr=$(cat /sys/class/net/eth1/address | sed 's/\://g')
  bt_addr=$(max $eth0_addr $eth1_addr)
  bt_addr=$((0x$bt_addr+1))
  bt_addr=$(printf '%012X' $bt_addr)

  BT_MACADDR=$(echo $bt_addr | sed 's/\(..\)/\1:/g;s/:$//')
}

# Set BT firmware based on WIFI SDIO ID
bt_set_firmware()
{
	# Check if WIFI SDIO ID matches Sterling LWB5 SDIO ID
	if [ "$(cat ${WIFI_SDIO_ID_FILE})" = "${WIFI_5G_SDIO_ID}" ]; then
		BT_FIRMWARE=${BT_FIRMWARE_LWB5}
	else
		BT_FIRMWARE=${BT_FIRMWARE_LWB}
	fi
}

# Enable BT via GPIO(s)
bt_enable()
{
	bt_buffer_enable

	# Power up BT module
	gpioset -t 0 --chip ${BT_EN_GPIO}=0
	sleep 1
	gpioset -t 0 --chip ${BT_EN_GPIO}=1
}

# Start BT hardware
bt_start()
{
	# Exit if BT module is not available
	wifi_sdio_exist ${WIFI_SDIO_ID_FILE} || exit 0

	# Exit if BT module is not bcm43xx
	verify_sdio_id ${WIFI_SDIO_ID_FILE} ${WIFI_2G_SDIO_ID} ${WIFI_5G_SDIO_ID} || exit 0

	# Enable BT hardware
	bt_enable

	# Set BT firmware file 
	bt_set_firmware

	# Set BT MAC addresss
	bt_set_macaddr

	# Start BT firmware loading service
	kill -9 $(pidof brcm_patchram_plus) 2>/dev/null || true
	brcm_patchram_plus \
			--patchram ${BT_FIRMWARE} \
			--enable_hci \
			--bd_addr ${BT_MACADDR} \
			--no2bytes \
			--baudrate 3000000 \
			--scopcm=1,0,0,0,0,0,0,0,0,0 \
			--tosleep 1000 ${BT_TTY_DEV} &
}

# Stop BT hardware
bt_stop()
{
	# Exit if BT module is not bcm43xx
	verify_sdio_id ${WIFI_SDIO_ID_FILE} ${WIFI_2G_SDIO_ID} ${WIFI_5G_SDIO_ID} || exit 0

	# Exit if BT interface is not available
	[ -e /sys/class/bluetooth/hci0 ] || exit 0

	# Stop BT interface
	hciconfig hci0 down

	# Stop BT firmware loading service
	kill -9 $(pidof brcm_patchram_plus) 2>/dev/null || true

  	# Power down BT module
	gpioset -t 0 --chip ${BT_EN_GPIO}=0

	bt_buffer_disable
}

###########################
#  Execution starts here  #
###########################
case $1 in

start)
	bt_start
	;;
stop)
	bt_stop
	;;
esac

exit 0
