#!/bin/sh -e
#
# Activate WIFI on Variscite VAR-SOM-MX7
#

# Include common functions
. /etc/wifi/variscite-wireless

# GPIO pin to enable WIFI module
WIFI_EN_GPIO="gpiochip0 4"

# GPIO pin to enable BT module
BT_EN_GPIO="gpiochip0 14"

# WIFI MMC host
WIFI_MMC_HOST=30b50000.mmc
WIFI_MMC_PATH="/sys/bus/platform/drivers/sdhci-esdhc-imx"

# Function to disable a network interface
disable_network_interface() {
	local iface="$1"

	# Check if the interface exists
	if ip link show "$iface" >/dev/null 2>&1; then
		ifconfig "$iface" down
		usleep 100000
	fi
}

# Check if wifi is bcm43xx
wifi_is_bcm43xx() {
	local magic

	# Check for EEPROM v2 magic indicating NOT BCM43xx
	magic=$(i2cget -f -y 0 0x50 0x00 w 2>/dev/null)

	if [ "$magic" = "0x3745" ]; then
		return 1
	fi

	return 0
}

# Power up WIFI chip
wifi_up()
{
	# Unbind WIFI device from MMC controller
	wifi_mmc_unbind ${WIFI_MMC_PATH} ${WIFI_MMC_HOST}

	# WLAN_EN up
	gpioset -t 0 --chip ${WIFI_EN_GPIO}=1

	# BT_EN up
	gpioset -t 0 --chip ${BT_EN_GPIO}=1

	# Wait 150ms at least
	usleep 200000

	# BT_EN down
	gpioset -t 0 --chip ${BT_EN_GPIO}=0

	# Bind WIFI device to MMC controller
	wifi_mmc_bind ${WIFI_MMC_PATH} ${WIFI_MMC_HOST}

	# Load WIFI driver
	modprobe brcmfmac
}

# Power down WIFI chip
wifi_down()
{
	# Disable network interface
	disable_network_interface wlan0

	# Unload WIFI driver
	modprobe -r brcmfmac

	# Unbind WIFI device from MMC controller
	wifi_mmc_unbind ${WIFI_MMC_PATH} ${WIFI_MMC_HOST}

	# WLAN_EN down
	gpioset -t 0 --chip ${WIFI_EN_GPIO}=0

	# BT_EN down
	gpioset -t 0 --chip ${BT_EN_GPIO}=0
}

# Return true if WIFI should be started
wifi_should_not_be_started()
{
	if ! wifi_is_bcm43xx; then
		return 0
	fi

	# Do not enable WIFI if it is already up
	[ -d /sys/class/net/wlan0 ] && return 0

	return 1
}

# Return true if WIFI should not be stopped
wifi_should_not_be_stopped()
{
	if ! wifi_is_bcm43xx; then
		return 0
	fi

	return 1
}

# Start WIFI hardware
wifi_start()
{
	# Exit if WIFI should not be started
	wifi_should_not_be_started && exit 0

	# Try starting WIFI hardware
	for i in $(seq 1 3); do
		# Up WIFI
		wifi_up

		# Exit if WIFI interface exists
		wifi_interface_exists "wlan0" && exit 0

		# Down WIFI
		wifi_down

		# Wait enough time for discharge
		sleep 5
	done

	exit 1
}

# Stop WIFI hardware
wifi_stop()
{
	# Exit if WIFI should not be stopped
	wifi_should_not_be_stopped && exit 0

	# Down WIFI
	wifi_down
}

###########################
#  Execution starts here  #
###########################
case $1 in
start)
	wifi_start
	;;
stop)
	wifi_stop
	;;
esac

exit 0
