#!/bin/sh -e

readonly FILE_SCRIPT="$(basename "$0")"
readonly DIR_SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source ${DIR_SCRIPT}/variscite-rproc-common.sh

readonly FILE_DEFAULT_FW=${FILE_DEFAULT_FW_U_BOOT}
readonly DIR_FW="/boot"

# Parse firmware file from command line
parse_args "$@"

# Determine if DDR or TCM
if [[ "$FILE_CM_BIN" == *"ddr"* ]]; then
    echo "Configuring for DDR memory"
    CM_LOAD_ADDR=${CM_LOAD_ADDR_DDR}
    CM_LOAD_ADDR_AUXVIEW=${CM_LOAD_ADDR_AUXVIEW_DDR}
else
    echo "Configuring for TCM memory"
    CM_LOAD_ADDR=${CM_LOAD_ADDR_TCM}
    CM_LOAD_ADDR_AUXVIEW=${CM_LOAD_ADDR_AUXVIEW_TCM}
fi

if [ "${CM_CORES}" -gt 1 ]; then
    CM_CORE_UBOOT="${CM_CORE}"
else
    CM_CORE_UBOOT=""
fi

# Configure U-Boot environment variables
if [ "i.MX8QM" = "${SOC}" ] || [ "i.MX8QXP" = "${SOC}" ]; then
    # i.MX8QM and i.MX8QXP always load to DDR, and u-boot copies to TCM
    set -x
else
    set -x
    fw_setenv ${CM_SERIES}_addr "${CM_LOAD_ADDR}"
fi
fw_setenv fdt_file "${CM_DTB}"
fw_setenv use_${CM_SERIES}${CM_CORE_UBOOT} "yes"
fw_setenv ${CM_SERIES}${CM_CORE_UBOOT}_bin "${FILE_CM_BIN}"

{ set +x; } 2>/dev/null
if [ "i.MX93" == ${SOC} ]; then
    # Some platforms have demos which have unused clocks from Linux
    # Ensure these stay enabled, otherwise some demos may not run
    # correctly.
    KERNELARGS=$(fw_printenv kernelargs -n)
    grep -vq clk_ignore_unused <<< "${KERNELARGS}"
    if [ "$?" -eq "0" ]; then
        set -x
        fw_setenv kernelargs "${KERNELARGS} clk_ignore_unused"
    else
        set -x
    fi
fi

# CPUs like the Cortex-M33 on i.MX9 series use the M core's
# address view for bootaux command.
{ set +x; } 2>/dev/null
if [ ! -z ${CM_LOAD_ADDR_AUXVIEW} ]; then
    set -x
    fw_setenv ${CM_SERIES}_addr_auxview "${CM_LOAD_ADDR_AUXVIEW}"
fi

{ set +x; } 2>/dev/null

echo
echo "Finished: Please reboot, the ${CM_SERIES} firmware will run during U-Boot"
echo
