#!/bin/sh -e
#
# Activate Bluetooth on Variscite DART-MX8M-PLUS/VAR-SOM-MX8M-PLUS
#

# Include common functions
. /etc/wifi/variscite-wireless
. /etc/gpiochip

gpio1=$(get_gpiochip "30200000.gpio")
gpio2=$(get_gpiochip "30210000.gpio")

# GPIO pin to enable BT module on DART-MX8M-PLUS
BT_EN_GPIO_DART="${gpio2} 6"

# GPIO pin to enable BT module
BT_EN_GPIO_SOM="${gpio2} 9"

# GPIO pin to control routing of UART signals
# to BT module or SOM connector on DART-MX8M-PLUS
BT_BUF_GPIO_DART="${gpio2} 9"

# GPIO pin to control routing of UART signals
# to BT module or SOM connector on VAR-SOM-MX8M-PLUS
BT_BUF_GPIO_SOM="${gpio1} 4"

# btnxpuart fdt device compatible file
BT_FDT_SOM="/sys/firmware/devicetree/base/soc@0/bus@30800000/serial@30880000/bluetooth_iw61x"
BT_FDT_DART="/sys/firmware/devicetree/base/soc@0/bus@30800000/serial@30a60000/bluetooth_iw61x"

# Return true if SOM is VAR-SOM-MX8M-PLUS
som_is_var_som_mx8m_plus()
{
	grep -q VAR-SOM-MX8M-PLUS /sys/devices/soc0/machine
}

# Set UART device connected to BT module
bt_set_vars()
{
	if som_is_var_som_mx8m_plus; then
		BT_FDT=${BT_FDT_SOM}
		BT_EN_GPIO=${BT_EN_GPIO_SOM}
		BT_BUF_GPIO=${BT_BUF_GPIO_SOM}
	else
		BT_FDT=${BT_FDT_DART}
		BT_EN_GPIO=${BT_EN_GPIO_DART}
		BT_BUF_GPIO=${BT_BUF_GPIO_DART}
	fi
}

# Use btnxpuart device node to determine if wifi module is iw61x
fdt_has_btnxpuart() {
	# Check if compatible file exists
	if [ ! -e "$BT_FDT/compatible" ]; then
		return 1
	fi

	# Check if compatible with nxp,88w8987-bt
	if ! grep -q "nxp,88w8987-bt" "$BT_FDT/compatible"; then
		return 1
	fi

	# Check if status file exists
	if [ ! -e "$BT_FDT/status" ]; then
		return 1
	fi

	# Check if status is okay
	if ! grep -q "okay" "$BT_FDT/status"; then
		return 1
	fi

	return 0
}

# Enable BT via GPIO(s)
bt_enable()
{
	# Power up BT module
	gpioset ${BT_EN_GPIO}=0
	sleep 0.1
	gpioset ${BT_EN_GPIO}=1
	sleep 0.1

	# Route UART lines to BT module
	gpioset ${BT_BUF_GPIO}=0
}

# Start BT hardware
bt_start()
{
	# Configure global variables for SOM or DART
	bt_set_vars

	# Exit if BT module is not iw612 according to the device tree
	fdt_has_btnxpuart || exit 0

	# Exit if BT interface is already running
	if [ -e "/sys/class/bluetooth/hci0" ]; then
		echo "$(basename $0): Bluetooth already started"
		exit 0
	fi

	echo "$(basename $0): starting"

	# Enable BT hardware
	bt_enable

	# Load the NXP bluetooth driver
	modprobe btnxpuart

	# Wait until the HCI interface comes up
	if ! timeout 10 sh -c 'until hciconfig | grep -q "hci"; do sleep 0.1; done'; then
		echo "Error: HCI interface did not come up"
		exit 1
	fi

	# Wait until the Bluetooth MAC address is not 00:00:00:00:00:00
	if ! timeout 10 sh -c 'until [ "$(hciconfig | grep "BD Address" | \
	awk "{print \$3}")" != "00:00:00:00:00:00" ]; do sleep 0.1; done'; then
		echo "Error: Bluetooth MAC address is 00:00:00:00:00:00"
		exit 1
	fi

	sleep 1

	# Fork a dummy process to satisfy the variscite-bt systemd service type=forking
	(while true; do sleep 60; done) &
}

# Stop BT hardware
bt_stop()
{
	# Configure global variables for SOM or DART
	bt_set_vars

	# Exit if BT module is not iw612 according to the device tree
	fdt_has_btnxpuart || exit 0

	# Exit if BT interface is not available
	[ -e /sys/class/bluetooth/hci0 ] || exit 0

	echo "$(basename $0): stopping"

	# Bring up hci interface before unloading the BT module to allow the driver
	# to restore the baud rate to 115200bps and conditionally issue reset command
	hciconfig hci0 up

	# Unload the driver
	modprobe -r btnxpuart

	# Assert bluetooth/802.15.4 reset GPIO and disable BT uart buffer
	gpioset ${BT_BUF_GPIO}=0
	gpioset ${BT_EN_GPIO}=0
}

# Issue in-band reset using hci interface
in_band_reset()
{
	# Exit if BT module is not iw612 according to the device tree
	fdt_has_btnxpuart || exit 0

	# Exit if BT interface is not available
	[ -e /sys/class/bluetooth/hci0 ] || exit 0

	echo "$(basename $0): in-band reset"

	# Bring up hci interface before using hci commands
	hciconfig hci0 up

	# Issue the reset command
	hcitool cmd 0x3f 0xfc 0
}


###########################
#  Execution starts here  #
###########################
case $1 in

start)
	bt_start
	;;
stop)
	bt_stop
	;;
in-band-reset)
	in_band_reset
	;;
esac

exit 0
